### ISSUE TITLE
how to run and were to put?

### ISSUE THREAD

**Issue by PressStart10** [rottytooth/Folders#5]
i downloaded and there was no desc. on how to run/ where to put the files.

**Comment by PressStart10** [comment]
pleas help

**Comment by rottytooth** [comment]
Hi there. You want to compile the compiler itself, which is here: https://github.com/rottytooth/Folders/tree/main/Rottytooth.Esolang.Folders -- then follow the instructions on that readme: in a terminal, type Folders [path] where [path] leads to the root directory of a Folders program, such as this one https://github.com/rottytooth/Folders/tree/main/Rottytooth.Esolang.Folders.SamplePrograms/99Bottles

**Comment by PressStart10** [comment]
i don't have a compiler
where do i get one

**Comment by PressStart10** [comment]
and i don't know wat to compile





@rottytooth
